version: 2

project_name: gofmtnginx

env:
  - GO111MODULE=on

builds:
  - id: gofmtnginx
    main: ./cmd/gofmtnginx/main.go
    binary: gofmtnginx-{{.Os}}-{{.Arch}}
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    # ensures mod timestamp to be the commit timestamp
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      # trims path
      - -trimpath
    ldflags:
      # use commit date instead of current date as main.date
      # only needed if you actually use those things in your main package, otherwise can be ignored.
      - -s -w -X github.com/ChrisMcKee/gofmtnginx/v1.Version={{.Version}}
    ignore:
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm
  
checksum:
  name_template: checksums.txt

source:
  enabled: true

sboms:
  - artifacts: archive
  - id: source # Two different sbom configurations need two different IDs
    artifacts: source

signs:
  - artifacts: package
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

nfpms:
  - id: packages
    package_name: gofmtnginx
    homepage: https://github.com/ChrisMcKee/gofmtnginx
    maintainer: Chris McKee <pcdevils@gmail.com>
    description: Recursively formats a directory tree of nginx configs
    license: MIT
    bindir: /usr/bin
    builds:
      - gofmtnginx
    formats:
      - apk
      - deb
      - rpm

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - ^Merge

archives:
  - id: archive_binaries
    format: binary
    name_template: "{{ .Binary }}"
    builds:
      - gofmtnginx

  - id: archive_default
    format: tar.gz
    builds:
      - gofmtnginx
